### ISSUE TITLE
希望能丰富一下css样式

### ISSUE THREAD

**Issue by ipan233** [idealclover/AISummary-Typecho#2]

**Comment by myvica** [comment]
这个就不错
```css
.aisummary {
    background-color: #2C3E50;
    color: white;
    padding: 20px;
    border-radius: 10px;
    margin-bottom: 1rem;
}
```
